### ISSUE TITLE
User input truncated/deleted if too long

### ISSUE THREAD

**Issue by FatherDivine** [vanshksingh/M5Cardputer-Chat-with-Gemini-API#3]
Currently, if the user's input is too long (like typing "Please create a PowerShell script based on the theory of relativity") by the time you get to what would be line #2, the first line disappears/is deleted. I couldn't return to the first line by pressing the '<-/del' key as this makes it worse.  The answer may be adding a scrolling ability in general, as if the answer from Gemini is too long it seems to truncate as well (meaning the inability to scroll back up or down to view past chat history).

Sure the fix is simple. I'm hoping someone adventurous can work on it. If not I'll give it a shot perhaps on the weekend.

Great work on creating this. I can see a lot of use already

**Comment by vanshksingh** [comment]
I have Uploaded the fixes in the gemini-development folder for right now , I will merge it with main code after final touches and clean up on 15th May 


And also thank you for the kind words !

**Comment by vanshksingh** [comment]
Added auto scroll in text input field with delete support , and scrolling up and down in response field using arrow keys in v0.1.0 release
