### ISSUE TITLE
WiFi fatal error

### ISSUE THREAD

**Issue by sklobi** [vanshksingh/M5Cardputer-Chat-with-Gemini-API#4]
It won’t connect to WiFi. How to make it so it does connect to my WiFi? Can I do this on my cardputer, in the Gemini app? I gave it my API key, why can’t I type in my WiFi network? Then takes me to this screen… no chat 
![image](https://github.com/vanshksingh/M5Cardputer-Chat-with-Gemini-API/assets/101013927/eff65677-6775-4264-be5e-2cb90361a41d)
![image](https://github.com/vanshksingh/M5Cardputer-Chat-with-Gemini-API/assets/101013927/1b49a609-2d36-4339-b296-2f62661bf832)

**Comment by vanshksingh** [comment]
use fn + .       (Down arrow)

and go to update configuration , there you can set wifi ssid , wifi password , and api key 

once set it generates an config file on the sd card , which you can then update from there itself also

**Comment by sklobi** [comment]
Is there a way to update config file without having to retype the API key? Cuz I just did it again only to have it fail connecting to WiFi again. I think it’s cuz I didn’t use all capitols for my network. I typed “Netgear78” instead of NETGEAR78. That matters correct?
