### ISSUE TITLE
Is there a way to update config file without having to retype the API key? Cuz I just did it again only to have it fail connecting to WiFi again. I think it’s cuz I didn’t use all capitols for my network. I typed “Netgear78” instead of NETGEAR78. That matters correct?

### ISSUE THREAD

**Issue by sklobi** [vanshksingh/M5Cardputer-Chat-with-Gemini-API#5]
Is there a way to update config file without having to retype the API key? Cuz I just did it again only to have it fail connecting to WiFi again. I think it’s cuz I didn’t use all capitols for my network. I typed “Netgear78” instead of NETGEAR78. That matters correct?

_Originally posted by @sklobi in https://github.com/vanshksingh/M5Cardputer-Chat-with-Gemini-API/issues/4#issuecomment-2118729005_

**Comment by vanshksingh** [comment]
Yes the capital letters matter , put your sd card in your computer , open the config.txt and edit that , put that back in the cardputer , this way you don't need to rewrite the api , also , wifi connection is a bit hit or miss at my place also , so after making sure the credentials are correct , try to connect 2-3 times :)
